### ISSUE TITLE
Cannot drag connection from socket after update to 2.0.1

### ISSUE THREAD

**Issue by ghost** [retejs/connection-path-plugin#18]
Hello,
after updating to 2.0.1 of this plugin, I experienced the following issue:
1. I create some nodes  (e.g. "START ,B ,C")
![image](https://github.com/retejs/connection-path-plugin/assets/118907052/6ea7f8bc-9460-47a5-ab4b-24a21bd85bbd)

2. I connect B and C with a connection
![image](https://github.com/retejs/connection-path-plugin/assets/118907052/4f7ec4a7-b77a-4019-a31b-1ce6650ad4b4)

4. The output socket from START can not be dragged anymore to create a connection
![image](https://github.com/retejs/connection-path-plugin/assets/118907052/6ded48a2-5b60-474c-907f-19322dd3022c)

As mentioned above, when downgrading this plugin to v2.0.0, this issue does not occur.
My other environment:
* Angular 15
* ReteJS 2.0.2
* Browser: Chrome 118.0.5993.70
* Other Rete Plugins: Angular Render, Selectable Nodes, History Plugin

I'm not sure how the corresponding change from 2.0.0 to 2.0.1 has caused this behaviour (after I've looked into the PR #17 )

**Comment by Ni55aN** [comment]
Thanks for reporting, I'm fixing it

**Comment by Ni55aN** [comment]
Fixed in v2.0.2 https://github.com/retejs/connection-path-plugin/pull/19#issuecomment-1772694293
