### ISSUE TITLE
Vertical flow with top and bottom sockets

### ISSUE THREAD

**Issue by Githamza** [retejs/connection-path-plugin#6]
Actually sockets are positioned on the left and right side , is it possible to make a vertical graph with sockets on top ( input ) and bottom ( output ) , if yes is the b`rete-arrange-plugin`  able to arrange them ?

**Comment by Ni55aN** [comment]
> to make a vertical graph

https://github.com/retejs/connection-plugin/issues/3#issuecomment-423817014

> with sockets on top ( input ) and bottom ( output )

Implement custom node component

> is the rete-arrange-plugin able to arrange them

```js
editor.use(AutoArrangePlugin, { vertical: true });
```

**Comment by Githamza** [comment]
great ! thanks
