### ISSUE TITLE
error on editor.use(ConnectionPathPlugin)

### ISSUE THREAD

**Issue by cslotterback** [retejs/connection-path-plugin#8]
I am getting the error 
`TypeError: t.install is not a function`
when trying to load the connection path plugin

`<script src="https://cdn.jsdelivr.net/npm/rete-connection-path-plugin@0.3.1/build/connection-path-plugin.min.js"></script>`

`editor.use(ConnectionPathPlugin);`

**Comment by ghost** [comment]
I have same issue

**Comment by emanuelperpetuo** [comment]
Try:

<script src="https://cdn.jsdelivr.net/npm/rete-connection-path-plugin@0.3.1/build/connection-path-plugin.min.js"></script>

editor.use(ConnectionPathPlugin.default);
